platform :ios, '6.0'

xcodeproj 'Example'

pod 'MSCollectionViewCalendarLayout', :path => '../'

pod 'RestKit', '~> 0.20'
pod 'CupertinoYankee', '~> 0.1'
pod 'UIColor-Utilities', '~> 1.0'
pod 'Masonry', '~> 0.2'
