platform :ios, '6.0'

xcodeproj 'Example'

pod 'MSCollectionViewCalendarLayout', :path => '../'

pod 'RestKit', '~> 0.22.0'
pod 'CupertinoYankee', '~> 0.1.0'
pod 'UIColor-HexString', '~> 1.0.0'
pod 'Masonry', '~> 0.4.0'
